"""make more columns an index

Revision ID: a50a51bc73fc
Revises: ba84349899ef
Create Date: 2025-06-29 11:12:04.541405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a50a51bc73fc'
down_revision: Union[str, None] = 'ba84349899ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('states')
    op.drop_index('ix_parameters_name', table_name='parameters')
    op.drop_table('parameters')
    op.drop_index('ix_sensors_name', table_name='sensors')
    op.drop_table('sensors')
    op.drop_index('ix_entities_name', table_name='entities')
    op.drop_table('entities')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entities',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('sensor_id', sa.INTEGER(), nullable=True),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('unit', sa.VARCHAR(), nullable=True),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_entities_name', 'entities', ['name'], unique=False)
    op.create_table('sensors',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), nullable=True),
    sa.Column('address', sa.VARCHAR(), nullable=True),
    sa.Column('key', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sensors_name', 'sensors', ['name'], unique=1)
    op.create_table('parameters',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), nullable=True),
    sa.Column('value', sa.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_parameters_name', 'parameters', ['name'], unique=1)
    op.create_table('states',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('entity_id', sa.INTEGER(), nullable=True),
    sa.Column('state', sa.VARCHAR(length=255), nullable=True),
    sa.Column('created', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
